Vagrant.configure("2") do |config|
  config.vm.define "master" do |master|
	master.vm.box = "ubuntu/xenial64"
	master.vm.hostname = "c1-master1"
	master.vm.network "private_network", ip: "192.168.99.100"
  end

  config.vm.define "snode1" do |snode1|
	snode1.vm.box = "ubuntu/xenial64"
	snode1.vm.hostname = "c1-node1"
	snode1.vm.network "private_network", ip: "192.168.99.200"
  end

  config.vm.define "snode2" do |snode2|
	snode2.vm.box = "ubuntu/xenial64"
	snode2.vm.network "private_network", ip: "192.168.99.300"
	snode2.vm.hostname = "c1-node2"
  end

  config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
  end
end
