Vagrant.configure("2") do |config|
  config.vm.define "kubemaster" do |kubemaster|
	kubemaster.vm.box = "ubuntu/xenial64"
	kubemaster.vm.hostname = "kubemaster"
	kubemaster.vm.network "private_network", ip: "192.168.99.100"
  kubemaster.vm.provision :shell, path: "Vagrant.bootstrap.sh"
  end

  config.vm.define "kubenode1" do |kubenode1|
	kubenode1.vm.box = "ubuntu/xenial64"
	kubenode1.vm.hostname = "kubenode1"
	kubenode1.vm.network "private_network", ip: "192.168.99.200"
  kubenode1.vm.provision :shell, path: "Vagrant.bootstrap.sh"
  end

  config.vm.define "kubenode2" do |kubenode2|
	kubenode2.vm.box = "ubuntu/xenial64"
	kubenode2.vm.hostname = "kubenode2"
  kubenode2.vm.network "private_network", ip: "192.168.99.300"
  kubenode2.vm.provision :shell, path: "Vagrant.bootstrap.sh"
  end

  config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
  end
end
