source 'http://rubygems.org'
#source 'http://nexus:8081/content/repositories/rubygemsproxy/'

gem 'cucumber', '2.4.0'
gem 'rspec', '3.5.0'
gem 'selenium-webdriver', '2.53.4'
gem 'watir-webdriver', '0.9.1'
gem 'require_all', '1.3.3'
gem 'activesupport', '4.1.8'
gem 'rake', '11.2.2'
gem 'simplecov', '0.12.0'
gem 'simplecov-rcov', '0.2.3'
gem 'rest-client', '2.0.0'


# gem to connect to saucelabs and also dynamically change browser parameters
gem 'saucelabs', '0.5'
gem 'nokogiri', '1.6.8'






