# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define "ubuntu" do |myubuntu|
	myubuntu.vm.box = "ubuntu/trusty64"
	myubuntu.vm.hostname = "myubuntu"
	myubuntu.vm.network "private_network", ip: "192.168.33.10"
  end
 config.vm.define "ubuntu1" do |myubuntu1|
	myubuntu1.vm.box = "ubuntu/trusty64"
	myubuntu1.vm.hostname = "myubuntu1"
	myubuntu1.vm.network "private_network", ip: "192.168.33.20"
  end

  config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
  end
end