source 'http://rubygems.org'
#source 'http://nexus:8081/content/repositories/rubygemsproxy/'

gem 'cucumber', '2.4.0'
gem 'rspec', '3.5.0'
gem 'require_all', '1.3.3'
gem 'rest-client', '2.0.0'
gem 'json', '2.0.1'
